server:
  port: 0
eureka:  
  client:
    serviceUrl:
      defaultZone: http://serverdiscovery:8761/eureka/
spring:
    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.8.105:3306/test?serverTimezone=UTC
      username: test
      password: test
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
      format_sql: true

swagger2.package: pe.com.claro
#    rabbitmq:
#      host: 192.168.8.105
#      port: 5672
#      username: test
#      password: test      
      
entity.manager.packagesToScan: pe.com.claro
application.name: salesorderapi
