server:
  port: 0
spring:
    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.40:3306/test?serverTimezone=UTC
      username: test
      password: test
      connectionTimeout: 15
      
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
      format_sql: true
      unicode: true
      characterEncoding: utf8
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

swagger2.package: pe.com.claro
#    rabbitmq:
#      host: 192.168.8.105
#      port: 5672
#      username: test
#      password: test      
      
entity.manager.packagesToScan: pe.com.claro
application.name: salesorderapi
